Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -106,6 +106,8 @@ SOLUTION_FILE="$(get_project_sln_file "$BUILD_DIR")"
 
 dotnet --list-runtimes
 
+BUILD_RESULT=0
+
 if [[ ${#SOLUTION_FILE} -eq 0 ]]; then
 	# Get project file from build directory
 	PROJECT_FILE="$(get_project_file "$BUILD_DIR")"
@@ -120,7 +122,7 @@ if [[ ${#SOLUTION_FILE} -eq 0 ]]; then
 	cd "$BUILD_DIR"
 	
 	STARTUP_PROJECT="$BUILD_DIR/$APP_ASSEMBLY/$APP_ASSEMBLY.csproj"
-	dotnet publish "$STARTUP_PROJECT" --output "$BUILD_DIR/$RELEASE_DIR" --configuration Release --runtime linux-x64 --no-self-contained --verbosity detailed
+	dotnet publish "$STARTUP_PROJECT" --output "$BUILD_DIR/$RELEASE_DIR" --configuration Release --runtime linux-x64 --no-self-contained --verbosity detailed || BUILD_RESULT=$?
 
 	print "Listing published files:"
         ls -R "$BUILD_DIR/$RELEASE_DIR"
@@ -142,7 +144,19 @@ else
 	export PATH="$PATH:/app/.dotnet/tools"
 	dotnet tool run dotnet-ef migrations list --startup-project "$APP_ASSEMBLY" --context AppDbContext
 	dotnet tool run dotnet-ef database update --startup-project "$APP_ASSEMBLY" --context AppDbContext
-	dotnet publish "$SOLUTION_FILE" --output "$BUILD_DIR/$RELEASE_DIR" --configuration Release --runtime linux-x64 --no-self-contained --verbosity detailed
+	dotnet publish "$SOLUTION_FILE" --output "$BUILD_DIR/$RELEASE_DIR" --configuration Release --runtime linux-x64 --no-self-contained --verbosity detailed || BUILD_RESULT=$?
+fi
+
+# Check if the build failed
+if [[ $BUILD_RESULT -ne 0 ]]; then
+    echo "Build failed. Please check the logs above for detailed error messages."
+    exit 1
+fi
+
+# Ensure DLL exists
+if [[ ! -f "$BUILD_DIR/$RELEASE_DIR/$APP_ASSEMBLY.dll" ]]; then
+    echo "Error: DLL not found in the expected output directory."
+    exit 1
 fi
 
 # Remove src files in production machine
