Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -90,36 +90,42 @@ SOLUTION_FILE="$(get_project_sln_file "$BUILD_DIR")"
 
 dotnet --list-runtimes
 
-APP_ASSEMBLY=""
-RELEASE_DIR=""
-
 if [[ -z "$SOLUTION_FILE" ]]; then
 	PROJECT_FILE="$(get_project_file "$BUILD_DIR")"
 	APP_ASSEMBLY="$(get_project_name "$BUILD_DIR")"
 	print "The assembly name: ${APP_ASSEMBLY}"
-	echo "export APP_ASSEMBLY=\"$(get_project_name "$BUILD_DIR")\"" >> "$PROFILE_PATH"
+	echo "export APP_ASSEMBLY=\"$APP_ASSEMBLY\"" >> "$PROFILE_PATH"
 
 	RELEASE_DIR="${APP_ASSEMBLY}_Release"
-	echo "export RELEASE_DIR=\"${APP_ASSEMBLY}_Release\"" >> "$PROFILE_PATH"
+	echo "export RELEASE_DIR=\"$RELEASE_DIR\"" >> "$PROFILE_PATH"
 	cd "$BUILD_DIR"
-	dotnet publish "$PROJECT_FILE" --output "$BUILD_DIR/$RELEASE_DIR" --configuration Release --runtime linux-x64 --no-self-contained	
+	dotnet publish "$PROJECT_FILE" --output "$BUILD_DIR/$RELEASE_DIR" --configuration Release --runtime linux-x64 --no-self-contained --verbosity detailed
 else
 	APP_ASSEMBLY="$(get_start_project_name "$BUILD_DIR")"
 	print "The assembly name: ${APP_ASSEMBLY}"
-	echo "export APP_ASSEMBLY=\"$(get_start_project_name "$BUILD_DIR")\"" >> "$PROFILE_PATH"
+	echo "export APP_ASSEMBLY=\"$APP_ASSEMBLY\"" >> "$PROFILE_PATH"
 	
 	SOLUTION_NAME="$(get_project_sln_name "$BUILD_DIR")"
 	print "The solution name: ${SOLUTION_NAME}"
 	
 	RELEASE_DIR="${SOLUTION_NAME}_Release"
-	echo "export RELEASE_DIR=\"${SOLUTION_NAME}_Release\"" >> "$PROFILE_PATH"
+	echo "export RELEASE_DIR=\"$RELEASE_DIR\"" >> "$PROFILE_PATH"
 	cd "$BUILD_DIR"
 	dotnet new tool-manifest
 	dotnet tool install dotnet-ef --version 9.*
 	export PATH="$PATH:$BUILD_DIR/.dotnet/tools"
 	dotnet tool run dotnet-ef migrations list --startup-project "$APP_ASSEMBLY" --context AppDbContext
 	dotnet tool run dotnet-ef database update --startup-project "$APP_ASSEMBLY" --context AppDbContext
-	dotnet publish "$SOLUTION_FILE" --output "$BUILD_DIR/$RELEASE_DIR" --configuration Release --runtime linux-x64 --no-self-contained
+	dotnet publish "$SOLUTION_FILE" --output "$BUILD_DIR/$RELEASE_DIR" --configuration Release --runtime linux-x64 --no-self-contained --verbosity detailed
+fi
+
+print "Listing published files:"
+ls -R "$BUILD_DIR/$RELEASE_DIR"
+
+APP_DLL="$BUILD_DIR/$RELEASE_DIR/$APP_ASSEMBLY.dll"
+if [ ! -f "$APP_DLL" ]; then
+    echo "Error: DLL not found at $APP_DLL"
+    exit 1
 fi
 
 find -maxdepth 1 ! -name Procfile ! -name .profile.d ! -name .apt ! -name .dotnet ! -name .heroku ! -name node_modules ! -name "$RELEASE_DIR"  -exec rm -rv {} \; > /dev/null 2>&1;
